config/routes.rb
Rails.application.routes.draw do
  resources :veiculos, only: [:index, :show] do
    collection do
      get '/valores'                    => 'veiculos#search_by_price'
      get '/modelo/:modelo_id'          => 'veiculos#search_by_model'
      get '/modelo/:modelo_id/ano/:ano' => 'veiculos#search_by_year'
    end
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  resources :marcas, only: [:index, :show] do
    collection do
      get '/tipo/:tipo'           => 'marcas#search_by_type'
      get '/descricao/:descricao' => 'marcas#search_by_brand'
    end
  end

  resources :modelos, only: [:index, :show] do
    collection do
      get '/marca/:marca_id' => 'modelos#search_by_brand'
      get '/descricao/:descricao'    => 'modelos#search_by_model'
      get '/marca/:marca_id/ano/:ano' => 'modelos#search_by_year'
    end
  end

  mount Sidekiq:: Web, at: '/sidekiq'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
    has_many :modelos
end

app/models/modelo.rb
class Modelo < ApplicationRecord
  belongs_to :marca
  has_many :veiculos
end

app/models/user.rb
class User < ApplicationRecord
end

app/models/veiculo.rb
class Veiculo < ApplicationRecord
  belongs_to :modelo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
	
    include ActionController::HttpAuthentication::Basic::ControllerMethods
	before_action :authentication

	attr_accessor :current_user

    def authentication
        if user = authenticate_with_http_basic { |u, p| User.find_by(login: u, password: p)}
            @current_user = user
        else
            request_http_basic_authentication
        end
    end

end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  before_action :set_marca, only: %i[ show ]

  # GET /marcas or /marcas.json
  def index
    @marcas = Marca.all
    render json: @marcas
  end

  def search_by_type
    @marcas = Marca.where(tipo: params[:tipo])
    render json: @marcas
  end

  def search_by_brand
    @marcas = Marca.where("marcas.descricao ilike ?", "#{params[:descricao]}%")
    render json: @marcas
  end
  
  

  # GET /marcas/1 or /marcas/1.json
  def show
    render json: @marca
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_marca
    @marca = Marca.find(params[:id])
  end
end

app/controllers/modelos_controller.rb
class ModelosController < ApplicationController
  before_action :set_modelo, only: %i[ show ]

  # GET /modelos or /modelos.json
  def index
    @modelos = Modelo.all.paginate(page: params[:page], per_page: 30)
    render json: @modelos
  end

  # GET /modelos/1 or /modelos/1.json
  def show
    render json: @modelo
  end

  def search_by_brand
    @modelos = Modelo.where(marca_id: params[:marca_id])
    render json: @modelos
  end
  
  def search_by_model
    @modelos = Modelo.where("modelos.descricao ilike ?", "#{params[:descricao]}%")
    render json: @modelos
  end

  def search_by_year
    @modelos = Modelo.joins(:veiculos).where(marca_id: params[:marca_id], veiculos: {ano: params[:ano]})
    render json: @modelos
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modelo
      @modelo = Modelo.find(params[:id])
    end
end

app/controllers/veiculos_controller.rb
class VeiculosController < ApplicationController
  before_action :set_veiculo, only: %i[ show ]

  # GET /veiculos or /veiculos.json
  def index
    @veiculos = Veiculo.all.paginate(page: params[:page], per_page: 30)
    render json: @veiculos
  end

  # GET /veiculos/1 or /veiculos/1.json
  def show
    render json: @veiculo
  end

  def search_by_model
    @veiculos = Veiculo.where(modelo_id: params[:modelo_id])
    render json: @veiculos
  end

  def search_by_year
    @veiculos = Veiculo.where(modelo_id: params[:modelo_id], ano: params[:ano])
    render json: @veiculos
  end

  def search_by_price
    @veiculos = Veiculo.joins(modelo: :marca).where(marca: {tipo: params[:tipo]}, preco: (params[:start_value].to_f..params[:end_value].to_f))
    render json: @veiculos, each_serializer: VeiculoSerializer
  end
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_veiculo
      @veiculo = Veiculo.find(params[:id])
    end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/marcas_helper.rb
module MarcasHelper
end

app/helpers/modelos_helper.rb
module ModelosHelper
end

app/helpers/veiculos_helper.rb
module VeiculosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treinamento</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/marcas/_form.html.erb
<%= form_with(model: marca) do |form| %>
  <% if marca.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(marca.errors.count, "error") %> prohibited this marca from being saved:</h2>

      <ul>
        <% marca.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="field">
    <%= form.label :tipo %>
    <%= form.text_field :tipo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/marcas/edit.html.erb
<h1>Editing Marca</h1>

<%= render 'form', marca: @marca %>

<%= link_to 'Show', @marca %> |
<%= link_to 'Back', marcas_path %>

app/views/marcas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Marcas</h1>

<table>
  <thead>
    <tr>
      <th>Descricao</th>
      <th>Codigo</th>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @marcas.each do |marca| %>
      <tr>
        <td><%= marca.descricao %></td>
        <td><%= marca.codigo %></td>
        <td><%= marca.tipo %></td>
        <td><%= link_to 'Show', marca %></td>
        <td><%= link_to 'Edit', edit_marca_path(marca) %></td>
        <td><%= link_to 'Destroy', marca, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Marca', new_marca_path %>

app/views/marcas/new.html.erb
<h1>New Marca</h1>

<%= render 'form', marca: @marca %>

<%= link_to 'Back', marcas_path %>

app/views/marcas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Descricao:</strong>
  <%= @marca.descricao %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @marca.codigo %>
</p>

<p>
  <strong>Tipo:</strong>
  <%= @marca.tipo %>
</p>

<%= link_to 'Edit', edit_marca_path(@marca) %> |
<%= link_to 'Back', marcas_path %>

app/views/modelos/_form.html.erb
<%= form_with(model: modelo) do |form| %>
  <% if modelo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(modelo.errors.count, "error") %> prohibited this modelo from being saved:</h2>

      <ul>
        <% modelo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :marca_id %>
    <%= form.text_field :marca_id %>
  </div>

  <div class="field">
    <%= form.label :descricao %>
    <%= form.text_field :descricao %>
  </div>

  <div class="field">
    <%= form.label :codigo %>
    <%= form.text_field :codigo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/modelos/edit.html.erb
<h1>Editing Modelo</h1>

<%= render 'form', modelo: @modelo %>

<%= link_to 'Show', @modelo %> |
<%= link_to 'Back', modelos_path %>

app/views/modelos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Modelos</h1>

<table>
  <thead>
    <tr>
      <th>Marca</th>
      <th>Descricao</th>
      <th>Codigo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modelos.each do |modelo| %>
      <tr>
        <td><%= modelo.marca_id %></td>
        <td><%= modelo.descricao %></td>
        <td><%= modelo.codigo %></td>
        <td><%= link_to 'Show', modelo %></td>
        <td><%= link_to 'Edit', edit_modelo_path(modelo) %></td>
        <td><%= link_to 'Destroy', modelo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modelo', new_modelo_path %>

app/views/modelos/new.html.erb
<h1>New Modelo</h1>

<%= render 'form', modelo: @modelo %>

<%= link_to 'Back', modelos_path %>

app/views/modelos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @modelo.marca_id %>
</p>

<p>
  <strong>Descricao:</strong>
  <%= @modelo.descricao %>
</p>

<p>
  <strong>Codigo:</strong>
  <%= @modelo.codigo %>
</p>

<%= link_to 'Edit', edit_modelo_path(@modelo) %> |
<%= link_to 'Back', modelos_path %>

app/views/veiculos/_form.html.erb
<%= form_with(model: veiculo) do |form| %>
  <% if veiculo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(veiculo.errors.count, "error") %> prohibited this veiculo from being saved:</h2>

      <ul>
        <% veiculo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :modelo_id %>
    <%= form.text_field :modelo_id %>
  </div>

  <div class="field">
    <%= form.label :ano %>
    <%= form.number_field :ano %>
  </div>

  <div class="field">
    <%= form.label :cod_fipe %>
    <%= form.text_field :cod_fipe %>
  </div>

  <div class="field">
    <%= form.label :preco %>
    <%= form.text_field :preco %>
  </div>

  <div class="field">
    <%= form.label :combustivel %>
    <%= form.text_field :combustivel %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/veiculos/edit.html.erb
<h1>Editing Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Show', @veiculo %> |
<%= link_to 'Back', veiculos_path %>

app/views/veiculos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Veiculos</h1>

<table>
  <thead>
    <tr>
      <th>Modelo</th>
      <th>Ano</th>
      <th>Cod fipe</th>
      <th>Preco</th>
      <th>Combustivel</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @veiculos.each do |veiculo| %>
      <tr>
        <td><%= veiculo.modelo_id %></td>
        <td><%= veiculo.ano %></td>
        <td><%= veiculo.cod_fipe %></td>
        <td><%= veiculo.preco %></td>
        <td><%= veiculo.combustivel %></td>
        <td><%= link_to 'Show', veiculo %></td>
        <td><%= link_to 'Edit', edit_veiculo_path(veiculo) %></td>
        <td><%= link_to 'Destroy', veiculo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Veiculo', new_veiculo_path %>

app/views/veiculos/new.html.erb
<h1>New Veiculo</h1>

<%= render 'form', veiculo: @veiculo %>

<%= link_to 'Back', veiculos_path %>

app/views/veiculos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Modelo:</strong>
  <%= @veiculo.modelo_id %>
</p>

<p>
  <strong>Ano:</strong>
  <%= @veiculo.ano %>
</p>

<p>
  <strong>Cod fipe:</strong>
  <%= @veiculo.cod_fipe %>
</p>

<p>
  <strong>Preco:</strong>
  <%= @veiculo.preco %>
</p>

<p>
  <strong>Combustivel:</strong>
  <%= @veiculo.combustivel %>
</p>

<%= link_to 'Edit', edit_veiculo_path(@veiculo) %> |
<%= link_to 'Back', veiculos_path %>